version: '2'

services:
  nginx:
    build: ./nginx
    container_name: nginx-https-proxy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./letsencrypt:/etc/letsencrypt
